### ISSUE TITLE
Common:countdown

### ISSUE THREAD

**Issue by myano** [Kays/sophia#42]
Add a countdown module like jenni has. It can countdown to arbitrary given dates.

!countdown 2012 12 21
607-days 23-hours 58-minutes until 2012 12 21

**Comment by Kays** [comment]
Perhaps a different date format would be nice. :)

**Comment by myano** [comment]
Such as? I think the YYYY MM DD is best because it's less arbitrary than the MM DD YYYY versus DD MM YYYY that is commonly confusing between international people. Where as YYYY MM DD is never confused with YYYY DD MM because YYYY DD MM is not used anywhere.

**Comment by Kays** [comment]
!countdown 12/21 ?

Generally, we can assume that countdown should not count down to a time in the past. Ergo, there's little check needed for having a year. Of course, I assume someone can countdown to a date 2 years in the future, but that's pretty useless because it's still such a long gap. I think a more useful feature is this:

!countdown set newsouthpark 2012 04 27 20 00   # though the numbers can be confusing if written like that
Then have that work with:
!countdown newsouthpark

What do you think? Much more useful than counting down an arbitrary date.
